Improve output with functions

diff --git a/bin/clean b/bin/clean
--- a/bin/clean
+++ b/bin/clean
@@ -2,13 +2,21 @@
 
 set -euo pipefail
 
+DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
+FUNCTIONS="${DIR}/functions"
+
+if [ -e "$FUNCTIONS" ]; then
+  source "$FUNCTIONS"
+else
+  printf "\n ⚠️ functions not found!\n"
+  exit 1
+fi
+
 # ==============================================================================
 # APPS
 # ==============================================================================
 
-echo
-echo "Closing apps"
-echo
+title "Closing apps"
 
 foregroundAppsString=$(osascript -e 'tell application "System Events" to get name of (processes where background only is false)')
 IFS=',' read -r -a foregroundApps <<<"$foregroundAppsString"
@@ -19,68 +27,71 @@ for foregroundApp in "${foregroundApps[@]}"; do
     osascript -e 'quit app "'"$appName"'"'
   fi
 done
+print_success "Done!"
 
 # ==============================================================================
 # PROCESSES
 # ==============================================================================
 
-echo
-echo "Quitting processes"
-echo
+title "Quitting processes"
 
 tmux kill-server || true
 killall node || true
+print_success "Done!"
 
 # ==============================================================================
 # DOTFILES
 # ==============================================================================
 
-echo
-echo "Pulling latest dotfiles and shell scripts"
-echo
+# title "Pulling latest dotfiles and shell scripts"
 
 # cd "$HOME/repos/dotfiles"
-# git pull
+# git pull --rebase
+# print_success "Done!"
 
 # ==============================================================================
 # HOMEBREW CLEANUP
 # ==============================================================================
 
-echo
-echo "Removing Homebrew artifacts"
-echo
+title "Removing Homebrew artifacts"
 
 brew -v cleanup
+print_success "Done!"
 
 # ==============================================================================
 # MACOS ARTIFACTS
 # ==============================================================================
 
-echo
-echo "Removing OS artifacts"
-echo
+title "Removing OS artifacts"
 
 cd "$HOME"
 find . -type f -name '*.DS_Store' -ls -delete
+print_success "Done!"
 
 # ==============================================================================
 # GIT-DELETE-SQUASHED
 # ==============================================================================
 
-echo
-echo "Removing merged local branches in each git repo"
-echo
+title "Removing merged local branches in each git repo"
 
 cd "$HOME/repos"
 find . -name .git -type d -execdir git-delete-squashed --dry-run ';'
+print_success "Done!"
 
 # ==============================================================================
 # REPO STATES
 # ==============================================================================
 
-echo
-echo "Checking the status of each git repo"
-echo
+title "Checking the status of each git repo"
 
 cd "$HOME/repos"
 deep-git-status
+
+# ==============================================================================
+# SHUTDOWN
+# ==============================================================================
+
+echo
+if ask "Do you want to shut down your computer?" Y; then
+  osascript -e 'tell app "loginwindow" to «event aevtrsdn»'
+fi
diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -2,6 +2,16 @@
 
 set -euo pipefail
 
+DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
+FUNCTIONS="${DIR}/functions"
+
+if [ -e "$FUNCTIONS" ]; then
+  source "$FUNCTIONS"
+else
+  printf "\n ⚠️ functions not found!\n"
+  exit 1
+fi
+
 # Ask for the administrator password upfront
 sudo -v
 
@@ -12,8 +22,7 @@ while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &
 # HOME
 # ==============================================================================
 
-echo "------------------------------"
-echo "Adding home folders"
+title "Adding home folders"
 
 home_folders=(
   ".ctags.d"
@@ -28,25 +37,26 @@ home_folders=(
 for home_folder in "${home_folders[@]}"; do
   mkdir -p "${HOME}/$home_folder"
 done
+print_success "Done!"
 
 # ==============================================================================
 # MACOS
 # ==============================================================================
 
-echo "------------------------------"
-echo "Updating macOS. If this requires a restart, run the script again."
+title "Updating macOS. If this requires a restart, run the script again."
 
 sudo softwareupdate -iaR --verbose
+print_success "Done!"
 
 # ==============================================================================
 # XCODE COMMAND LINE TOOLS
 # ==============================================================================
 
 if [ -f "$(xcode-select -v)" ]; then
-  echo "------------------------------"
-  echo "Installing Xcode Command Line Tools"
+  title "Installing Xcode Command Line Tools"
 
   xcode-select --install
+  print_success "Done!"
 fi
 
 # ==============================================================================
@@ -54,17 +64,16 @@ fi
 # ==============================================================================
 
 if [ -f "$(brew -v)" ]; then
-  echo "------------------------------"
-  echo "Installing Homebrew"
+  title "Installing Homebrew"
 
   /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
+  print_success "Done!"
 fi
 
-echo "------------------------------"
-echo "Installing global Homebrew packages"
+title "Installing global Homebrew packages"
 
-brew update
-brew upgrade
+brew -v update
+brew upgrade --force-bottle
 
 homebrew_packages=(
   "git"
@@ -79,7 +88,9 @@ for homebrew_package in "${homebrew_packages[@]}"; do
   brew install "$homebrew_package"
 done
 
-brew cleanup
+brew -v cleanup
+brew -v doctor
+print_success "Done!"
 
 # ==============================================================================
 # ZPLUG
@@ -87,10 +98,10 @@ brew cleanup
 
 ZPLUG_DIR="${HOME}/.zplug"
 if [ ! -s "$ZPLUG_DIR" ]; then
-  echo "------------------------------"
-  echo "Installing zplug"
+  title "Installing zplug"
 
   curl -sL --proto-redir -all,https https://raw.githubusercontent.com/zplug/installer/master/installer.zsh | zsh
+  print_success "Done!"
 fi
 
 # ==============================================================================
@@ -99,11 +110,11 @@ fi
 
 VIMPLUG_DIR="${HOME}/.local/share/nvim/site/autoload/plug.vim"
 if [ ! -s "$VIMPLUG_DIR" ]; then
-  echo "------------------------------"
-  echo "Installing vim-plug"
+  title "Installing vim-plug"
 
   curl -fLo "$VIMPLUG_DIR" --create-dirs \
     https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
+  print_success "Done!"
 fi
 
 # ==============================================================================
@@ -112,14 +123,17 @@ fi
 
 TPM_DIR="${HOME}/.tmux/plugins/tpm"
 if [ ! -s "$TPM_DIR" ]; then
-  echo "------------------------------"
-  echo "Installing Tmux Plugin Manager"
+  title "Installing Tmux Plugin Manager"
 
   git clone https://github.com/tmux-plugins/tpm "$TPM_DIR"
+  print_success "Done!"
 fi
 
 # ==============================================================================
 # RESTART
 # ==============================================================================
 
-sudo shutdown -r now
+echo
+if ask "Do you want to restart your computer?" Y; then
+  osascript -e 'tell app "loginwindow" to «event aevtrrst»'
+fi
